#!/bin/sh

set -e

cd "$(dirname "$0")/.."

git clone https://github.com/tensorflow/models.git
curl -o models/research/audioset/yamnet/yamnet.h5 https://storage.googleapis.com/audioset/yamnet.h5
curl -o models/research/audioset/vggish/vggish_model.ckpt https://storage.googleapis.com/audioset/vggish_model.ckpt
curl -o models/research/audioset/vggish/vggish_pca_params.npz https://storage.googleapis.com/audioset/vggish_pca_params.npz
